In [1]:
import pandas as pd

### creating,reading df

In [2]:
pd.DataFrame({'group A' : [7,11],
              'group B' : [2,9]},
              index = ['votes for cats','votes for dogs'])

                group A  group B
votes for cats        7        2
votes for dogs       11        9

In [3]:
pd.Series([7,11],index = ['day','month'],name = 'humi\'s birthday')

day       7
month    11
Name: humi's birthday, dtype: int64

In [4]:
data = pd.read_csv('wine_reviews.csv')

In [5]:
data.shape

(150930, 11)

In [6]:
data.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
1,1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez
2,2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley
3,3,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi
4,4,France,"This is the top wine from La Bégude, named aft...",La Brûlade,95,66.0,Provence,Bandol,NaN,Provence red blend,Domaine de la Bégude

In [7]:
data = pd.read_csv('wine_reviews.csv',index_col = 0)

In [8]:
data.head()

,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez
2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley
3,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi
4,France,"This is the top wine from La Bégude, named aft...",La Brûlade,95,66.0,Provence,Bandol,NaN,Provence red blend,Domaine de la Bégude

In [9]:
animals = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
animals

        Cows  Goats
Year 1    12     22
Year 2    20     19

In [10]:
animals.to_csv('animals.csv')

### indexing, selecting and assigning

In [11]:
data.country
data['country']
# both are to call a particular column named country

0             US
1          Spain
2             US
3             US
4         France
           ...
150925     Italy
150926    France
150927     Italy
150928    France
150929     Italy
Name: country, Length: 150930, dtype: object

In [12]:
data.country[0]        
data['country'][0]
# to call first element of the column country

'US'

In [13]:
# indexing with iloc (index locator)
data.iloc[0]                              # gives the first row of the dataframe

country                                                       US
description    This tremendous 100% varietal wine hails from ...
designation                                    Martha's Vineyard
points                                                        96
price                                                      235.0
province                                              California
region_1                                             Napa Valley
region_2                                                    Napa
variety                                       Cabernet Sauvignon
winery                                                     Heitz
Name: 0, dtype: object

In [14]:
data.iloc[:,0]                                # gives the first column of the dataframe

0             US
1          Spain
2             US
3             US
4         France
           ...
150925     Italy
150926    France
150927     Italy
150928    France
150929     Italy
Name: country, Length: 150930, dtype: object

In [15]:
data.iloc[:7,2:5]                       # first 7 elements of the second to fourth column

                            designation  points  price
0                     Martha's Vineyard      96  235.0
1  Carodorum Selección Especial Reserva      96  110.0
2         Special Selected Late Harvest      96   90.0
3                               Reserve      96   65.0
4                            La Brûlade      95   66.0
5                             Numanthia      95   73.0
6                             San Román      95   65.0

In [16]:
data.iloc[-5:]                     # to get the last 5 rows of the dataset

,country,description,designation,points,price,province,region_1,region_2,variety,winery
150925,Italy,Many people feel Fiano represents southern Ita...,NaN,91,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Feudi di San Gregorio
150926,France,"Offers an intriguing nose with ginger, lime an...",Cuvée Prestige,91,27.0,Champagne,Champagne,NaN,Champagne Blend,H.Germain
150927,Italy,This classic example comes from a cru vineyard...,Terre di Dora,91,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Terredora
150928,France,"A perfect salmon shade, with scents of peaches...",Grand Brut Rosé,90,52.0,Champagne,Champagne,NaN,Champagne Blend,Gosset
150929,Italy,More Pinot Grigios should taste like this. A r...,NaN,90,15.0,Northeastern Italy,Alto Adige,NaN,Pinot Grigio,Alois Lageder

In [17]:
data.iloc[[1,2,3],:5]                      # we can also pass a list of rows, we obtain rows of index 1,2,3 and first 5 columns

,country,description,designation,points,price
1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0
2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0
3,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0

In [18]:
data.iloc[data.points.idxmin()]

country                                                Argentina
description    Tropical, soapy aromas are yeasty and flat. Fl...
designation                                                  NaN
points                                                        80
price                                                       13.0
province                                        Mendoza Province
region_1                                                 Mendoza
region_2                                                     NaN
variety                                               Chardonnay
winery                                              Tres Exilios
Name: 7793, dtype: object

In [19]:
data.loc[:,'country']           # here we can use the column name , when the dataset has well defined columns

0             US
1          Spain
2             US
3             US
4         France
           ...
150925     Italy
150926    France
150927     Italy
150928    France
150929     Italy
Name: country, Length: 150930, dtype: object

In [20]:
data.loc[[1,2,3],'country']

1    Spain
2       US
3       US
Name: country, dtype: object

In [21]:
data.loc[:,['country','points','price']]

       country  points  price
0           US      96  235.0
1        Spain      96  110.0
2           US      96   90.0
3           US      96   65.0
4       France      95   66.0
...        ...     ...    ...
150925   Italy      91   20.0
150926  France      91   27.0
150927   Italy      91   20.0
150928  France      90   52.0
150929   Italy      90   15.0

[150930 rows x 3 columns]

In [22]:
data.set_index('country')

,description,designation,points,price,province,region_1,region_2,variety,winery
country,,,,,,,,,
US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez
US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley
US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi
France,"This is the top wine from La Bégude, named aft...",La Brûlade,95,66.0,Provence,Bandol,NaN,Provence red blend,Domaine de la Bégude
...,...,...,...,...,...,...,...,...,...
Italy,Many people feel Fiano represents southern Ita...,NaN,91,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Feudi di San Gregorio
France,"Offers an intriguing nose with ginger, lime an...",Cuvée Prestige,91,27.0,Champagne,Champagne,NaN,Champagne Blend,H.Germain
Italy,This classic example comes from a cru vineyard...,Terre di Dora,91,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Terredora
France,"A perfect salmon shade, with scents of peaches...",Grand Brut Rosé,90,52.0,Champagne,Champagne,NaN,Champagne Blend,Gosset
Italy,More Pinot Grigios should taste like this. A r...,NaN,90,15.0,Northeastern Italy,Alto Adige,NaN,Pinot Grigio,Alois Lageder

In [23]:
data.country == 'US'

0          True
1         False
2          True
3          True
4         False
          ...
150925    False
150926    False
150927    False
150928    False
150929    False
Name: country, Length: 150930, dtype: bool

In [24]:
data.loc[(data.country == 'US') & (data.points >= 90)]

,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley
3,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi
8,US,This re-named vineyard was formerly bottled as...,Silice,95,65.0,Oregon,Chehalem Mountains,Willamette Valley,Pinot Noir,Bergström
9,US,The producer sources from two blocks of the vi...,Gap's Crown Vineyard,95,60.0,California,Sonoma Coast,Sonoma,Pinot Noir,Blue Farm
...,...,...,...,...,...,...,...,...,...,...
150788,US,"This Chard has always been dependably rich, an...",Byron Vineyard,90,32.0,California,Santa Maria Valley,Central Coast,Chardonnay,Byron
150790,US,"Always a bit herbaceous, this year the underly...",Meritage,90,28.0,California,Sonoma County,Sonoma,Bordeaux-style Red Blend,Dry Creek Vineyard
150914,US,"Old-gold in color, and thick and syrupy. The a...",Late Harvest Cluster Select,94,25.0,California,Anderson Valley,Mendocino/Lake Counties,White Riesling,Navarro
150915,US,"Decades ago, Beringer’s then-winemaker Myron N...",Nightingale,93,30.0,California,North Coast,North Coast,White Blend,Beringer
150916,US,An impressive wine that presents a full bouque...,J. Schram,93,65.0,California,Napa Valley,Napa,Champagne Blend,Schramsberg

### conditional selectors

In [25]:
data.loc[data.country.isin(['Italy','France'])]

,country,description,designation,points,price,province,region_1,region_2,variety,winery
4,France,"This is the top wine from La Bégude, named aft...",La Brûlade,95,66.0,Provence,Bandol,NaN,Provence red blend,Domaine de la Bégude
10,Italy,"Elegance, complexity and structure come togeth...",Ronco della Chiesa,95,80.0,Northeastern Italy,Collio,NaN,Friulano,Borgo del Tiglio
13,France,This wine is in peak condition. The tannins an...,Château Montus Prestige,95,90.0,Southwest France,Madiran,NaN,Tannat,Vignobles Brumont
18,France,Coming from a seven-acre vineyard named after ...,Le Pigeonnier,95,290.0,Southwest France,Cahors,NaN,Malbec,Château Lagrézette
32,Italy,"Underbrush, scorched earth, menthol and plum s...",Vigna Piaggia,90,NaN,Tuscany,Brunello di Montalcino,NaN,Sangiovese,Abbadia Ardenga
...,...,...,...,...,...,...,...,...,...,...
150925,Italy,Many people feel Fiano represents southern Ita...,NaN,91,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Feudi di San Gregorio
150926,France,"Offers an intriguing nose with ginger, lime an...",Cuvée Prestige,91,27.0,Champagne,Champagne,NaN,Champagne Blend,H.Germain
150927,Italy,This classic example comes from a cru vineyard...,Terre di Dora,91,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Terredora
150928,France,"A perfect salmon shade, with scents of peaches...",Grand Brut Rosé,90,52.0,Champagne,Champagne,NaN,Champagne Blend,Gosset
150929,Italy,More Pinot Grigios should taste like this. A r...,NaN,90,15.0,Northeastern Italy,Alto Adige,NaN,Pinot Grigio,Alois Lageder

In [26]:
data.loc[data.price.isnull()]

,country,description,designation,points,price,province,region_1,region_2,variety,winery
32,Italy,"Underbrush, scorched earth, menthol and plum s...",Vigna Piaggia,90,NaN,Tuscany,Brunello di Montalcino,NaN,Sangiovese,Abbadia Ardenga
56,France,"Delicious while also young and textured, this ...",Le Pavé,90,NaN,Loire Valley,Sancerre,NaN,Sauvignon Blanc,Domaine Vacheron
72,Italy,"This offers aromas of red rose, wild berry, da...",Bussia Riserva,91,NaN,Piedmont,Barolo,NaN,Nebbiolo,Silvano Bolmida
82,Italy,"Berry, baking spice, dried iris, mint and a hi...",Palliano Riserva,91,NaN,Piedmont,Roero,NaN,Nebbiolo,Ceste
116,Spain,Aromas of brandied cherry and crème de cassis ...,Dulce Tinto,86,NaN,Levante,Jumilla,NaN,Monastrell,Casa de la Ermita
...,...,...,...,...,...,...,...,...,...,...
150377,New Zealand,"Light and a bit herbal, like a pleasant St.-Jo...",Matheson,84,NaN,Hawke's Bay,NaN,NaN,Syrah,Matua Valley
150378,New Zealand,"Impressive purple color, but less intense on t...",NaN,84,NaN,Martinborough,NaN,NaN,Syrah,Kusuda
150587,Canada,"Shows pronounced oily, earthy, almost tobacco-...",Icewine,90,NaN,Ontario,Lake Erie North Shore,NaN,Riesling,Colio
150673,US,"Cherry-scented, clean and fruity. Good concent...",NaN,87,NaN,California,Dry Creek Valley,Sonoma,Zinfandel,Taft Street
150922,Italy,Made by 30-ish Roberta Borghese high above Man...,Superiore,91,NaN,Northeastern Italy,Colli Orientali del Friuli,NaN,Tocai,Ronchi di Manzano

In [27]:
data['index_backwards'] = range(len(data), 0,-1)
data['index_backwards']

0         150930
1         150929
2         150928
3         150927
4         150926
           ...
150925         5
150926         4
150927         3
150928         2
150929         1
Name: index_backwards, Length: 150930, dtype: int64

In [28]:
desc = data.description

In [29]:
first_decsription = data.description[0]
first_decsription

'This tremendous 100% varietal wine hails from Oakville and was aged over three years in oak. Juicy red-cherry fruit and a compelling hint of caramel greet the palate, framed by elegant, fine tannins and a subtle minty tone in the background. Balanced and rewarding from start to finish, it has years ahead of it to develop further nuance. Enjoy 2022–2030.'

In [30]:
desc.loc[0]
data.description.iloc[0]
data.description.loc[0]

'This tremendous 100% varietal wine hails from Oakville and was aged over three years in oak. Juicy red-cherry fruit and a compelling hint of caramel greet the palate, framed by elegant, fine tannins and a subtle minty tone in the background. Balanced and rewarding from start to finish, it has years ahead of it to develop further nuance. Enjoy 2022–2030.'

In [31]:
first_row = data.iloc[0]
first_row

country                                                           US
description        This tremendous 100% varietal wine hails from ...
designation                                        Martha's Vineyard
points                                                            96
price                                                          235.0
province                                                  California
region_1                                                 Napa Valley
region_2                                                        Napa
variety                                           Cabernet Sauvignon
winery                                                         Heitz
index_backwards                                               150930
Name: 0, dtype: object

In [32]:
first_10_descriptions = data.description.iloc[:10]
first_10_descriptions = desc[:10]
first_10_descriptions

0    This tremendous 100% varietal wine hails from ...
1    Ripe aromas of fig, blackberry and cassis are ...
2    Mac Watson honors the memory of a wine once ma...
3    This spent 20 months in 30% new French oak, an...
4    This is the top wine from La Bégude, named aft...
5    Deep, dense and pure from the opening bell, th...
6    Slightly gritty black-fruit aromas include a s...
7    Lush cedary black-fruit aromas are luxe and of...
8    This re-named vineyard was formerly bottled as...
9    The producer sources from two blocks of the vi...
Name: description, dtype: object

In [33]:
sample_reviews = data.iloc[[1,2,3,5,8],]               # can give colon as well such as data.iloc[[1,2,3,5,8],:]
sample_reviews

,country,description,designation,points,price,province,region_1,region_2,variety,winery,index_backwards
1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez,150929
2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley,150928
3,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi,150927
5,Spain,"Deep, dense and pure from the opening bell, th...",Numanthia,95,73.0,Northern Spain,Toro,NaN,Tinta de Toro,Numanthia,150925
8,US,This re-named vineyard was formerly bottled as...,Silice,95,65.0,Oregon,Chehalem Mountains,Willamette Valley,Pinot Noir,Bergström,150922

In [34]:
index = [1,2,3,5,8]
sample_reviews = data.loc[index]
sample_reviews

,country,description,designation,points,price,province,region_1,region_2,variety,winery,index_backwards
1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez,150929
2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley,150928
3,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi,150927
5,Spain,"Deep, dense and pure from the opening bell, th...",Numanthia,95,73.0,Northern Spain,Toro,NaN,Tinta de Toro,Numanthia,150925
8,US,This re-named vineyard was formerly bottled as...,Silice,95,65.0,Oregon,Chehalem Mountains,Willamette Valley,Pinot Noir,Bergström,150922

In [35]:
df = data.loc[[0,1,10,100],['country','province','region_1','region_2']]
df

    country            province     region_1     region_2
0        US          California  Napa Valley         Napa
1     Spain      Northern Spain         Toro          NaN
10    Italy  Northeastern Italy       Collio          NaN
100      US          California  South Coast  South Coast

In [36]:
df_1 = data.loc[:99,['country','province']]
df_1

   country          province
0       US        California
1    Spain    Northern Spain
2       US        California
3       US            Oregon
4   France          Provence
..     ...               ...
95  France  Southwest France
96      US        California
97      US        California
98  France  Southwest France
99  France  Southwest France

[100 rows x 2 columns]

In [37]:
italian_wines = data.loc[data.country == 'Italy']
italian_wines

,country,description,designation,points,price,province,region_1,region_2,variety,winery,index_backwards
10,Italy,"Elegance, complexity and structure come togeth...",Ronco della Chiesa,95,80.0,Northeastern Italy,Collio,NaN,Friulano,Borgo del Tiglio,150920
32,Italy,"Underbrush, scorched earth, menthol and plum s...",Vigna Piaggia,90,NaN,Tuscany,Brunello di Montalcino,NaN,Sangiovese,Abbadia Ardenga,150898
35,Italy,"Forest floor, tilled soil, mature berry and a ...",Riserva,90,135.0,Tuscany,Brunello di Montalcino,NaN,Sangiovese,Carillon,150895
37,Italy,"Aromas of forest floor, violet, red berry and ...",NaN,90,29.0,Tuscany,Vino Nobile di Montepulciano,NaN,Sangiovese,Avignonesi,150893
38,Italy,"This has a charming nose that boasts rose, vio...",NaN,90,23.0,Tuscany,Chianti Classico,NaN,Sangiovese,Casina di Cornia,150892
...,...,...,...,...,...,...,...,...,...,...,...
150920,Italy,"Rich and mature aromas of smoke, earth and her...",Brut Riserva,91,19.0,Northeastern Italy,Trento,NaN,Champagne Blend,Letrari,10
150922,Italy,Made by 30-ish Roberta Borghese high above Man...,Superiore,91,NaN,Northeastern Italy,Colli Orientali del Friuli,NaN,Tocai,Ronchi di Manzano,8
150925,Italy,Many people feel Fiano represents southern Ita...,NaN,91,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Feudi di San Gregorio,5
150927,Italy,This classic example comes from a cru vineyard...,Terre di Dora,91,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Terredora,3
150929,Italy,More Pinot Grigios should taste like this. A r...,NaN,90,15.0,Northeastern Italy,Alto Adige,NaN,Pinot Grigio,Alois Lageder,1

In [38]:
top_oceania_wines = data.loc[
    (data.country.isin(['Australia','New Zealand']))
    & (data.points >= 95)]
top_oceania_wines

,country,description,designation,points,price,province,region_1,region_2,variety,winery,index_backwards
2148,Australia,Full-bodied and plush yet vibrant and imbued w...,The Factor,98,125.0,South Australia,Barossa Valley,NaN,Shiraz,Torbreck,148782
2458,Australia,This is a top example of the classic Australia...,The Peake,96,150.0,South Australia,McLaren Vale,NaN,Cabernet-Shiraz,Hickinbotham,148472
3033,Australia,This Cabernet equivalent to Grange has explode...,Bin 707,95,500.0,South Australia,South Australia,NaN,Cabernet Sauvignon,Penfolds,147897
3044,Australia,"From vines planted in 1912, this has been an i...",Mount Edelstone Vineyard,95,200.0,South Australia,Eden Valley,NaN,Shiraz,Henschke,147886
3047,Australia,"This is a throwback to those brash, flavor-exu...",One,95,95.0,South Australia,Langhorne Creek,NaN,Red Blend,Heartland,147883
...,...,...,...,...,...,...,...,...,...,...,...
122779,Australia,If Standish's Relic is the feminine side of Sh...,The Standish Single Vineyard,96,135.0,South Australia,Barossa Valley,NaN,Shiraz,Standish,28151
127614,Australia,This stellar wine takes a little time in the g...,Hill of Grace,95,625.0,South Australia,Eden Valley,NaN,Shiraz,Henschke,23316
137383,Australia,The 2007 Astralis impresses for its combinatio...,Astralis,95,225.0,South Australia,Clarendon,NaN,Syrah,Clarendon Hills,13547
150562,Australia,"As unevolved as they are, the dense and multil...",Grange,96,185.0,South Australia,South Australia,NaN,Shiraz,Penfolds,368
150563,Australia,"Seamless luxury from stem to stern, this ‘baby...",RWT,95,70.0,South Australia,Barossa Valley,NaN,Shiraz,Penfolds,367

In [39]:
median_point = data.points.median()

In [40]:
countries = data.country.unique()
countries

array(['US', 'Spain', 'France', 'Italy', 'New Zealand', 'Bulgaria',
       'Argentina', 'Australia', 'Portugal', 'Israel', 'South Africa',
       'Greece', 'Chile', 'Morocco', 'Romania', 'Germany', 'Canada',
       'Moldova', 'Hungary', 'Austria', 'Croatia', 'Slovenia', nan,
       'India', 'Turkey', 'Macedonia', 'Lebanon', 'Serbia', 'Uruguay',
       'Switzerland', 'Albania', 'Bosnia and Herzegovina', 'Brazil',
       'Cyprus', 'Lithuania', 'Japan', 'China', 'South Korea', 'Ukraine',
       'England', 'Mexico', 'Georgia', 'Montenegro', 'Luxembourg',
       'Slovakia', 'Czech Republic', 'Egypt', 'Tunisia', 'US-France'],
      dtype=object)

In [41]:
reviews_per_country = data.country.value_counts()

In [42]:
def remean_points_row(row):
    row.points = row.points - data.points.mean()
    return row
data.apply(remean_points_row,axis='columns')

,country,description,designation,points,price,province,region_1,region_2,variety,winery,index_backwards
0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,8.111582,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz,150930
1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,8.111582,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez,150929
2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,8.111582,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley,150928
3,US,"This spent 20 months in 30% new French oak, an...",Reserve,8.111582,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi,150927
4,France,"This is the top wine from La Bégude, named aft...",La Brûlade,7.111582,66.0,Provence,Bandol,NaN,Provence red blend,Domaine de la Bégude,150926
...,...,...,...,...,...,...,...,...,...,...,...
150925,Italy,Many people feel Fiano represents southern Ita...,NaN,3.111582,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Feudi di San Gregorio,5
150926,France,"Offers an intriguing nose with ginger, lime an...",Cuvée Prestige,3.111582,27.0,Champagne,Champagne,NaN,Champagne Blend,H.Germain,4
150927,Italy,This classic example comes from a cru vineyard...,Terre di Dora,3.111582,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Terredora,3
150928,France,"A perfect salmon shade, with scents of peaches...",Grand Brut Rosé,2.111582,52.0,Champagne,Champagne,NaN,Champagne Blend,Gosset,2
150929,Italy,More Pinot Grigios should taste like this. A r...,NaN,2.111582,15.0,Northeastern Italy,Alto Adige,NaN,Pinot Grigio,Alois Lageder,1

In [43]:
data.head()

,country,description,designation,points,price,province,region_1,region_2,variety,winery,index_backwards
0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz,150930
1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez,150929
2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley,150928
3,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi,150927
4,France,"This is the top wine from La Bégude, named aft...",La Brûlade,95,66.0,Provence,Bandol,NaN,Provence red blend,Domaine de la Bégude,150926

In [44]:
bargain_idx = (data.points / data.price).idxmax()
bargain_wine = data.loc[bargain_idx,'designation']

In [45]:
# Italy = data.country.map(lambda cnt : "Italy" in cnt).sum()
# France = data.country.map(lambda cnt : "France" in cnt).sum()
# descriptor_counts = pd.Series([Italy,France], index=['Italy','France'])
# descriptor_counts

In [46]:
def stars(rows):
    if rows.country == 'Canada':
        return 3
    elif rows.points >= 95:
        return 3
    elif rows.points >= 85:
        return 2
    else:
        return 1
star_ratings = data.apply(stars,axis = 'columns')
star_ratings

0         3
1         3
2         3
3         3
4         3
         ..
150925    2
150926    2
150927    2
150928    2
150929    2
Length: 150930, dtype: int64

In [47]:
data.groupby('points').points.count().sort_values(ascending=False)

points
87     20747
88     17871
90     15973
86     15573
89     12921
85     12411
84     10708
91     10536
92      9241
83      6048
93      6017
82      4041
94      3462
95      1716
81      1502
80       898
96       695
97       365
98       131
99        50
100       24
Name: points, dtype: int64

In [48]:
data.groupby('winery').apply(lambda df : df.iloc[0])

,country,description,designation,points,price,province,region_1,region_2,variety,winery,index_backwards
winery,,,,,,,,,,,
'37 Cellars,US,"The name refers to the year 1937, a classic ye...",NaN,88,NaN,Washington,Columbia Valley (WA),Columbia Valley,Cabernet Sauvignon,'37 Cellars,93309
1+1=3,Spain,"As in previous years, this wine just isn't tha...",Cabernet Sauvignon,82,18.0,Catalonia,Penedès,NaN,Rosé,1+1=3,85893
10 Knots,US,"Hot in alcohol, simple in everything else, thi...",Moonraker,81,35.0,California,Paso Robles,Central Coast,Grenache,10 Knots,114595
1000 Stories,US,Exotically fruity with an enticing floral char...,Bourbon Barrel Aged Batch No 13,90,19.0,California,California,California Other,Zinfandel,1000 Stories,146026
1040FU,US,"Unripe, with green peppercorn and asparagus no...",NaN,82,25.0,California,Santa Barbara County,Central Coast,Syrah,1040FU,23687
...,...,...,...,...,...,...,...,...,...,...,...
Ñandú,Argentina,The lighter-style nose that focuses on red plu...,NaN,82,17.0,Mendoza Province,Mendoza,NaN,Malbec,Ñandú,114597
Único Luis Miguel,Chile,From Ventisquero and the Mexican crooner Luis ...,Gran Reserva,85,15.0,Maipo Valley,NaN,NaN,Cabernet Sauvignon,Único Luis Miguel,80347
àMaurice,US,"While this wine starts out a bit reductive, it...",Gamache Vineyard,93,35.0,Washington,Columbia Valley (WA),Columbia Valley,Malbec,àMaurice,139640
áster,Spain,"Coconut and saline aromas fold in toast, berry...",Crianza,87,26.0,Northern Spain,Ribera del Duero,NaN,Tempranillo Blend,áster,101929
Štoka,Slovenia,This orange-style wine is dark straw in color ...,Grganja,90,23.0,Kras,NaN,NaN,Vitovska,Štoka,147757

In [49]:
data.groupby(['country','province']).apply(lambda df: df.loc[df.points.idxmin()])

                              country  \
country   province
Albania   Mirditë             Albania
Argentina Mendoza Province  Argentina
          Other             Argentina
Australia Australia Other   Australia
          New South Wales   Australia
...                               ...
Uruguay   Juanico             Uruguay
          Montevideo          Uruguay
          Progreso            Uruguay
          San Jose            Uruguay
          Uruguay             Uruguay

                                                                  description  \
country   province
Albania   Mirditë           This garnet-colored wine made from 100% Kallme...
Argentina Mendoza Province  Tropical, soapy aromas are yeasty and flat. Fl...
          Other             Weird, green, spicy and odd smelling, with har...
Australia Australia Other   Light and insubstantial in the mouth, with fla...
          New South Wales   Smells and tastes like the fruit juice blends ...
...                                                                       ...
Uruguay   Juanico           If it were only true that the stock black cher...
          Montevideo        A good example of South American Albariño, thi...
          Progreso          Concentrated, ripe aromas of blackberry and ca...
          San Jose          Straightforward and honest with aromas of Fern...
          Uruguay           The rubber and tree bark are common for Urugua...

                                      designation  points  price  \
country   province
Albania   Mirditë                             NaN      88   20.0
Argentina Mendoza Province                    NaN      80   13.0
          Other                     Martin Fierro      80   10.0
Australia Australia Other            Nottage Hill      80    9.0
          New South Wales               Rams Leap      81   12.0
...                                           ...     ...    ...
Uruguay   Juanico           Selección de Barricas      81   22.0
          Montevideo                          NaN      89   25.0
          Progreso                            RPF      88   22.0
          San Jose                            NaN      82   19.0
          Uruguay              Reserva del Virrey      80   18.0

                                    province                 region_1  \
country   province
Albania   Mirditë                    Mirditë                      NaN
Argentina Mendoza Province  Mendoza Province                  Mendoza
          Other                        Other             Tulum Valley
Australia Australia Other    Australia Other  South Eastern Australia
          New South Wales    New South Wales                   Mudgee
...                                      ...                      ...
Uruguay   Juanico                    Juanico                      NaN
          Montevideo              Montevideo                      NaN
          Progreso                  Progreso                      NaN
          San Jose                  San Jose                      NaN
          Uruguay                    Uruguay                      NaN

                           region_2             variety             winery  \
country   province
Albania   Mirditë               NaN             Kallmet             Arbëri
Argentina Mendoza Province      NaN          Chardonnay       Tres Exilios
          Other                 NaN  Cabernet Sauvignon    Bodegas Borbore
Australia Australia Other       NaN          Pinot Noir             Hardys
          New South Wales       NaN              Shiraz    Canonbah Bridge
...                             ...                 ...                ...
Uruguay   Juanico               NaN           Red Blend  Bodegones Del Sur
          Montevideo            NaN            Albariño              Bouza
          Progreso              NaN              Tannat             Pisano
          San Jose              NaN           Red Blend           Tanterra
          Uruguay               NaN              Tannat      Dante Irurtia

                            index_backwards
country   province
Albania   Mirditë                    146288
Argentina Mendoza Province           143137
          Other                      131580
Australia Australia Other             94100
          New South Wales             90680
...                                     ...
Uruguay   Juanico                     14198
          Montevideo                 144695
          Progreso                   143752
          San Jose                   104016
          Uruguay                     13912

[455 rows x 11 columns]

In [50]:
data.groupby(['country']).points.agg([min,max,len])

C:\Users\alihu\AppData\Local\Temp\ipykernel_15172\1012391292.py:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass 'min' instead.
  data.groupby(['country']).points.agg([min,max,len])
C:\Users\alihu\AppData\Local\Temp\ipykernel_15172\1012391292.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass 'max' instead.
  data.groupby(['country']).points.agg([min,max,len])

                        min  max    len
country
Albania                  88   88      2
Argentina                80   97   5631
Australia                80  100   4957
Austria                  81   98   3057
Bosnia and Herzegovina   83   88      4
Brazil                   81   88     25
Bulgaria                 80   90     77
Canada                   82   93    196
Chile                    80   95   5816
China                    82   82      3
Croatia                  81   91     89
Cyprus                   80   89     31
Czech Republic           85   87      6
Egypt                    83   84      3
England                  91   94      9
France                   80  100  21098
Georgia                  81   92     43
Germany                  80   97   2452
Greece                   80   92    884
Hungary                  80   96    231
India                    82   91      8
Israel                   80   93    630
Italy                    80  100  23478
Japan                    85   85      2
Lebanon                  81   91     37
Lithuania                84   85      8
Luxembourg               86   88      9
Macedonia                81   89     16
Mexico                   80   92     63
Moldova                  81   90     71
Montenegro               82   82      2
Morocco                  82   93     12
New Zealand              80   94   3320
Portugal                 80   99   5322
Romania                  80   92    139
Serbia                   86   89     14
Slovakia                 82   87      3
Slovenia                 82   92     94
South Africa             80   95   2258
South Korea              81   82      4
Spain                    80   98   8268
Switzerland              83   90      4
Tunisia                  85   87      2
Turkey                   84   92     52
US                       80  100  62397
US-France                88   88      1
Ukraine                  83   86      5
Uruguay                  80   90     92

In [51]:
best_rating_per_price = data.groupby('price')['points'].max().sort_index()
best_rating_per_price

price
4.0        86
5.0        90
6.0        90
7.0        90
8.0        91
         ...
1300.0     96
1400.0    100
1900.0     98
2013.0     91
2300.0     99
Name: points, Length: 357, dtype: int64

In [52]:
variety = data.groupby('variety').price.agg([min,max])
variety

C:\Users\alihu\AppData\Local\Temp\ipykernel_15172\2310822113.py:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass 'min' instead.
  variety = data.groupby('variety').price.agg([min,max])
C:\Users\alihu\AppData\Local\Temp\ipykernel_15172\2310822113.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass 'max' instead.
  variety = data.groupby('variety').price.agg([min,max])

                         min    max
variety
Agiorgitiko              8.0   65.0
Aglianico                6.0  130.0
Aidani                  27.0   27.0
Airen                    8.0   10.0
Albana                   8.0   66.0
...                      ...    ...
Zierfandler-Rotgipfler  20.0   25.0
Zinfandel                4.0  100.0
Zlahtina                13.0   17.0
Zweigelt                 9.0   70.0
Žilavka                 13.0   15.0

[632 rows x 2 columns]

In [53]:
sorted_varieties = variety.sort_values(by=['min','max'], ascending=False)
sorted_varieties

                                  min    max
variety
Cabernet-Shiraz                 150.0  150.0
Mazuelo                          92.0  105.0
Carignan-Syrah                   80.0   80.0
Syrah-Cabernet Franc             69.0   69.0
Nasco                            65.0   65.0
...                               ...    ...
Rabigato                          NaN    NaN
Sacy                              NaN    NaN
Sauvignon Blanc-Sauvignon Gris    NaN    NaN
Terret Blanc                      NaN    NaN
Zelen                             NaN    NaN

[632 rows x 2 columns]

In [54]:
country_variety_counts = data.groupby(['country','variety']).size().sort_values(ascending=False)
country_variety_counts

country      variety
US           Pinot Noir                  10340
             Cabernet Sauvignon           9178
             Chardonnay                   8127
France       Bordeaux-style Red Blend     4960
US           Syrah                        4274
                                         ...
France       Pied de Perdrix                 1
Tunisia      White Blend                     1
             Rosé                            1
Switzerland  White Blend                     1
US           Carignan-Grenache               1
Length: 1475, dtype: int64

In [55]:
data.price.dtype

dtype('float64')

In [56]:
data.dtypes

country             object
description         object
designation         object
points               int64
price              float64
province            object
region_1            object
region_2            object
variety             object
winery              object
index_backwards      int64
dtype: object

In [57]:
data.points.astype('float64')

0         96.0
1         96.0
2         96.0
3         96.0
4         95.0
          ...
150925    91.0
150926    91.0
150927    91.0
150928    90.0
150929    90.0
Name: points, Length: 150930, dtype: float64

In [58]:
data.index.dtype

dtype('int64')

In [59]:
data[pd.isna(data.country)]

,country,description,designation,points,price,province,region_1,region_2,variety,winery,index_backwards
1133,NaN,Delicate white flowers and a spin of lemon pee...,Askitikos,90,17.0,NaN,NaN,NaN,Assyrtiko,Tsililis,149797
1440,NaN,"A blend of 60% Syrah, 30% Cabernet Sauvignon a...",Shah,90,30.0,NaN,NaN,NaN,Red Blend,Büyülübağ,149490
68226,NaN,"From first sniff to last, the nose never makes...",Piedra Feliz,81,15.0,NaN,NaN,NaN,Pinot Noir,Chilcas,82704
113016,NaN,"From first sniff to last, the nose never makes...",Piedra Feliz,81,15.0,NaN,NaN,NaN,Pinot Noir,Chilcas,37914
135696,NaN,"From first sniff to last, the nose never makes...",Piedra Feliz,81,15.0,NaN,NaN,NaN,Pinot Noir,Chilcas,15234

In [60]:
country = data.country.fillna('unknown')
country.iloc[1132:1135]

1132         US
1133    unknown
1134     France
Name: country, dtype: object

In [61]:
pinot = data.variety.replace('Pinot Noir','Cat Noir')
pinot.iloc[:5]

0    Cabernet Sauvignon
1         Tinta de Toro
2       Sauvignon Blanc
3              Cat Noir
4    Provence red blend
Name: variety, dtype: object

In [62]:
points = data.points.astype('str')

In [63]:
null_price = data.price.isnull().sum()

# alternatively 
null_price = pd.isnull(data.price).sum()
null_price

13695

In [64]:
region_1 = data.region_1.fillna('Unknown')
region_1.value_counts(ascending=False)

# alternatively
# region_1 = data.region_1.fillna('Unknown).value_counts().sort_values(ascending = False)

region_1
Unknown                 25060
Napa Valley              6209
Columbia Valley (WA)     4975
Mendoza                  3586
Russian River Valley     3571
                        ...
Vallée du Paradis           1
Chignin-Bergeron            1
Roussette de Savoie         1
Savoie                      1
Coteaux du Tricastin        1
Name: count, Length: 1237, dtype: int64

In [65]:
renaming_columns = data.rename(columns = {'points':'score'})
renaming_columns

,country,description,designation,score,price,province,region_1,region_2,variety,winery,index_backwards
0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz,150930
1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez,150929
2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley,150928
3,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi,150927
4,France,"This is the top wine from La Bégude, named aft...",La Brûlade,95,66.0,Provence,Bandol,NaN,Provence red blend,Domaine de la Bégude,150926
...,...,...,...,...,...,...,...,...,...,...,...
150925,Italy,Many people feel Fiano represents southern Ita...,NaN,91,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Feudi di San Gregorio,5
150926,France,"Offers an intriguing nose with ginger, lime an...",Cuvée Prestige,91,27.0,Champagne,Champagne,NaN,Champagne Blend,H.Germain,4
150927,Italy,This classic example comes from a cru vineyard...,Terre di Dora,91,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Terredora,3
150928,France,"A perfect salmon shade, with scents of peaches...",Grand Brut Rosé,90,52.0,Champagne,Champagne,NaN,Champagne Blend,Gosset,2
150929,Italy,More Pinot Grigios should taste like this. A r...,NaN,90,15.0,Northeastern Italy,Alto Adige,NaN,Pinot Grigio,Alois Lageder,1

In [66]:
renaming_index = data.rename(index = { 0 : 'first index', 1 : ' second index'})
renaming_index

,country,description,designation,points,price,province,region_1,region_2,variety,winery,index_backwards
first index,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz,150930
second index,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez,150929
2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley,150928
3,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi,150927
4,France,"This is the top wine from La Bégude, named aft...",La Brûlade,95,66.0,Provence,Bandol,NaN,Provence red blend,Domaine de la Bégude,150926
...,...,...,...,...,...,...,...,...,...,...,...
150925,Italy,Many people feel Fiano represents southern Ita...,NaN,91,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Feudi di San Gregorio,5
150926,France,"Offers an intriguing nose with ginger, lime an...",Cuvée Prestige,91,27.0,Champagne,Champagne,NaN,Champagne Blend,H.Germain,4
150927,Italy,This classic example comes from a cru vineyard...,Terre di Dora,91,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Terredora,3
150928,France,"A perfect salmon shade, with scents of peaches...",Grand Brut Rosé,90,52.0,Champagne,Champagne,NaN,Champagne Blend,Gosset,2
150929,Italy,More Pinot Grigios should taste like this. A r...,NaN,90,15.0,Northeastern Italy,Alto Adige,NaN,Pinot Grigio,Alois Lageder,1

In [67]:
renaming_axis = data.rename_axis('wines',axis = 'rows').rename_axis('fields',axis = 'columns')
renaming_axis

fields,country,description,designation,points,price,province,region_1,region_2,variety,winery,index_backwards
wines,,,,,,,,,,,
0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz,150930
1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez,150929
2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley,150928
3,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi,150927
4,France,"This is the top wine from La Bégude, named aft...",La Brûlade,95,66.0,Provence,Bandol,NaN,Provence red blend,Domaine de la Bégude,150926
...,...,...,...,...,...,...,...,...,...,...,...
150925,Italy,Many people feel Fiano represents southern Ita...,NaN,91,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Feudi di San Gregorio,5
150926,France,"Offers an intriguing nose with ginger, lime an...",Cuvée Prestige,91,27.0,Champagne,Champagne,NaN,Champagne Blend,H.Germain,4
150927,Italy,This classic example comes from a cru vineyard...,Terre di Dora,91,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Terredora,3
150928,France,"A perfect salmon shade, with scents of peaches...",Grand Brut Rosé,90,52.0,Champagne,Champagne,NaN,Champagne Blend,Gosset,2
150929,Italy,More Pinot Grigios should taste like this. A r...,NaN,90,15.0,Northeastern Italy,Alto Adige,NaN,Pinot Grigio,Alois Lageder,1